"""initial

Revision ID: c21533a5578f
Revises: 
Create Date: 2025-04-13 11:59:55.957749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c21533a5578f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('tid', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('language_code', sa.Text(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.Column('gamed_premium_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('kind', sa.Integer(), server_default='0', nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
